version: '2'
services:
  spark-master:
    image: toandrew/spark-master:2.3.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
networks:
  default:
    external:
      name: xiaoyezi-overlay
