version: '2'
services:
  spark-worker-1:
    image: toandrew/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
networks:
  default:
    external:
      name: xiaoyezi-overlay
