version: '2'
services:
  spark-master:
    image: toandrew/spark-master:2.3.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    image: toandrew/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
